[general]
    name = "Mi Band 6"
    nameRegex = "Mi.*6"
    type = "Band"
    characteristicNames = ["heartRate"]
[heartRate]
    name = "Heart Rate"
    serviceUUID = "0000180d-0000-1000-8000-00805f9b34fb"
    characteristicUUID = "00002a37-0000-1000-8000-00805f9b34fb"
#   formula = ""


